"""add memory table

Revision ID: 5300d0038a27
Revises: db3ec7c2ca66
Create Date: 2026-08-05 08:26:07.381742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5300d0038a27'
down_revision: Union[str, Sequence[str], None] = 'db3ec7c2ca66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ai_employee_id', sa.UUID(), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=False),
    sa.Column('memory_value', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_employee_id'], ['ai_employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory')
    # ### end Alembic commands ###
